-- Persisted ASR/TTS provider settings managed by the settings page (MySQL 8+).
CREATE TABLE IF NOT EXISTS `voice_provider_config` (
  `id` INT NOT NULL DEFAULT 1,
  `api_key_ciphertext` VARCHAR(4096) NULL,
  `api_key_nonce` VARCHAR(64) NULL,
  `asr_url` VARCHAR(512) NOT NULL,
  `asr_model` VARCHAR(128) NOT NULL,
  `asr_language` VARCHAR(32) NOT NULL,
  `asr_format` VARCHAR(32) NOT NULL,
  `asr_sample_rate` INT NOT NULL,
  `asr_enable_turn_detection` BOOLEAN NOT NULL DEFAULT TRUE,
  `asr_turn_detection_type` VARCHAR(64) NOT NULL,
  `asr_turn_detection_threshold` DOUBLE NOT NULL DEFAULT 0,
  `asr_turn_detection_silence_duration_ms` INT NOT NULL DEFAULT 1000,
  `tts_model` VARCHAR(128) NOT NULL,
  `tts_voice` VARCHAR(64) NOT NULL,
  `tts_format` VARCHAR(32) NOT NULL,
  `tts_sample_rate` INT NOT NULL,
  `tts_mode` VARCHAR(32) NOT NULL,
  `tts_language_type` VARCHAR(64) NOT NULL,
  `tts_speech_rate` DOUBLE NOT NULL DEFAULT 1,
  `tts_volume` INT NOT NULL DEFAULT 60,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `ck_voice_provider_config_singleton` CHECK (`id` = 1),
  CONSTRAINT `ck_voice_provider_asr_sample_rate` CHECK (`asr_sample_rate` > 0),
  CONSTRAINT `ck_voice_provider_tts_sample_rate` CHECK (`tts_sample_rate` > 0),
  CONSTRAINT `ck_voice_provider_threshold` CHECK (`asr_turn_detection_threshold` BETWEEN 0 AND 1),
  CONSTRAINT `ck_voice_provider_silence` CHECK (`asr_turn_detection_silence_duration_ms` >= 0),
  CONSTRAINT `ck_voice_provider_speech_rate` CHECK (`tts_speech_rate` > 0),
  CONSTRAINT `ck_voice_provider_volume` CHECK (`tts_volume` BETWEEN 0 AND 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
