from enum import Enum
from typing import Optional

class ErrorCode(str, Enum):
    RESUME_NOT_FOUND = "RESUME_NOT_FOUND"
    RESUME_PARSE_FAILED = "RESUME_PARSE_FAILED"
    RESUME_ANALYSIS_NOT_FOUND = "RESUME_ANALYSIS_NOT_FOUND"
    SYSTEM_ERROR = "SYSTEM_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    FILE_TOO_LARGE_ERROR = "FILE_TOO_LARGE_ERROR"
    KB_NOT_FOUND = "KB_NOT_FOUND"
    KB_PARSE_FAILED = "KB_PARSE_FAILED"
    KB_VECTORIZE_ERROR = "KB_VECTORIZE_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    NOT_FOUND = "NOT_FOUND"
    INTERVIEW_SESSION_NOT_FOUND = "INTERVIEW_SESSION_NOT_FOUND"
    BAD_REQUEST = "BAD_REQUEST"
    AI_SERVICE_ERROR = "AI_SERVICE_ERROR"
    LLM_PROVIDER_NOT_FOUND = "LLM_PROVIDER_NOT_FOUND"
    LLM_PROVIDER_DISABLED = "LLM_PROVIDER_DISABLED"
    LLM_PROVIDER_CONFIG_ERROR = "LLM_PROVIDER_CONFIG_ERROR"
    LLM_PROVIDER_CRYPTO_ERROR = "LLM_PROVIDER_CRYPTO_ERROR"
    INTERVIEW_SCHEDULE_NOT_FOUND = "INTERVIEW_SCHEDULE_NOT_FOUND"
    INTERVIEW_QUESTION_NOT_FOUND = "INTERVIEW_QUESTION_NOT_FOUND"
    INTERVIEW_QUESTION_INSUFFICIENT = "INTERVIEW_QUESTION_INSUFFICIENT"
    INTERVIEW_QUESTION_GENERATION_FAILED = "INTERVIEW_QUESTION_GENERATION_FAILED"
    INTERVIEW_NOT_COMPLETED = "INTERVIEW_NOT_COMPLETED"
    EXPORT_PDF_FAILED = "EXPORT_PDF_FAILED"


class BusinessException(Exception):
    def __init__(self, code: ErrorCode, message: str, details: Optional[str] = None):
        super().__init__(message)
        self.code = code
        self.message = message
        self.details = details
